### ISSUE TITLE
To-do features (synced with Xifeng)

### ISSUE THREAD

**Issue by shanzhenren** [shanzhenren/StructMineDataInfra#30]
- [ ] query suggestion / auto-completion for entity type querying
- [ ] enable searching entity names directly
- [ ] enable rank-list-of-paper mode
- [ ] (optional) add table-view aside to the visualized graph, for better overview
